version: "3.8"
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - target: 80
        published: 88
        protocol: tcp
    configs:
    - source: nginx_conf
      target: /etc/nginx/nginx.conf
    - source: default_nginx
      target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: volume
        source: files
        target: /var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public
      - internal
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.newdesk.rule=Host(`newdesk.nhrs.ru`) || Host(`newdesk.zsmik.com`)"
        - "traefik.http.services.newdesk.loadbalancer.server.port=80" 
        - "traefik.http.services.newdesk.loadbalancer.sticky=true"
        - "traefik.http.services.newdesk.loadbalancer.sticky.cookie.name=newdesk"
        - "traefik.http.routers.newdesk.entrypoints=web"
        - "traefik.docker.network=traefik-public"
  redis:
    image: redis:7
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --appendonly yes
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure

  php-fpm:
    image: ilfatgub/php-fpm:7.2
    environment:
      TZ: "Asia/Yekaterinburg"
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_IP: ${SQL_IP}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_IP: ${SMTP_IP}
      cookieValidationKey: ${cookieValidationKey_newdesk}
    extra_hosts:
    - "${extra_host_logs}"
    - "${extra_host_tel}"
    configs:
      - source: php_ini_redis
        target: /usr/local/etc/php/conf.d/custom.ini
    volumes:
      - type: volume
        source: files
        target: /var/www/html
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure

configs:
  default_nginx:
    external: true
  nginx_conf:
    external: true
  php_ini_redis:
    external: true

volumes:
  files:
    driver_opts:
      type: nfs
      o: addr=${NFS_IP},rw,nolock
      device: ":/var/www/html/newdesk.nhrs.ru"

networks:
  traefik-public:
    external: true
  internal:
    driver: overlay